import { config } from "./config.js";
import { loadState, markProcessed } from "./state.js";
import { syncBaseBranch, createOrResetBranch, hasChanges, commitAll, pushBranch } from "./git.js";
import { runClaudeOnIssue } from "./claude.js";
import {
  listTargetIssues,
  findExistingPullRequest,
  createPullRequest,
  commentOnIssue,
  swapToDoneLabel,
} from "./github.js";

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "task";
}

function log(...args) {
  console.log(new Date().toISOString(), ...args);
}

async function processIssue(issue) {
  const branchName = `issue-${issue.number}-${slugify(issue.title)}`;
  log(`[#${issue.number}] processing "${issue.title}" on branch ${branchName}`);

  const existingPR = await findExistingPullRequest(branchName);
  if (existingPR) {
    log(`[#${issue.number}] PR #${existingPR.number} already exists for ${branchName}, skipping`);
    return;
  }

  await syncBaseBranch(config.repoPath, config.baseBranch);
  await createOrResetBranch(config.repoPath, branchName, config.baseBranch);

  await runClaudeOnIssue(config.repoPath, issue);

  if (!(await hasChanges(config.repoPath))) {
    log(`[#${issue.number}] Claude Code made no file changes, skipping PR`);
    await commentOnIssue(
      issue.number,
      "Claude Code ran but did not produce any file changes for this issue. Please check the issue description and retry."
    );
    return;
  }

  await commitAll(config.repoPath, `${issue.title} (#${issue.number})`);
  await pushBranch(config.repoPath, branchName);

  const pr = await createPullRequest({
    branchName,
    title: issue.title,
    body: `Closes #${issue.number}\n\n🤖 Automatically generated by issue-watcher + Claude Code.`,
  });
  log(`[#${issue.number}] opened PR #${pr.number}: ${pr.html_url}`);

  await commentOnIssue(issue.number, `Opened #${pr.number} to address this issue.`);
  await swapToDoneLabel(issue.number);
}

async function pollOnce(state) {
  const issues = await listTargetIssues();
  const newIssues = issues.filter((issue) => !state.processedIssues.includes(issue.number));

  for (const issue of newIssues) {
    try {
      await processIssue(issue);
    } catch (err) {
      log(`[#${issue.number}] failed:`, err.message);
      await commentOnIssue(issue.number, `Automated processing failed: ${err.message}`).catch(() => {});
    } finally {
      // Mark as processed even on failure so a persistently broken issue
      // doesn't spin the loop forever; remove its label and re-add TARGET_LABEL to retry.
      markProcessed(state, issue.number);
    }
  }
}

async function main() {
  const state = loadState();
  log(`issue-watcher started for ${config.owner}/${config.repo}, polling every ${config.pollIntervalMs}ms`);

  let stopping = false;
  const stop = () => {
    stopping = true;
    log("shutting down");
  };
  process.on("SIGINT", stop);
  process.on("SIGTERM", stop);

  while (!stopping) {
    try {
      await pollOnce(state);
    } catch (err) {
      log("poll failed:", err.message);
    }
    await new Promise((resolve) => setTimeout(resolve, config.pollIntervalMs));
  }
}

main();
